// EDITE O HORÁRIO AQUI. Exemplo: horario: '12:00'
const FESTA={data:'2026-12-19',horario:null};
const captions=['Nosso pequeno explorador','Um olhar cheio de curiosidade','Sempre descobrindo o mundo','Pronto para mais uma aventura','Amor em família','Colinho de pai','Pequenos passos, grandes descobertas','Carinho que abraça','Companheiros de aventura','Um passeio para lembrar','Descobertas em família','Diversão em família','Mais um momento especial'];
const gallery=document.getElementById('gallery'),dialog=document.getElementById('lightbox');let current=0,opener=null;
captions.forEach((caption,i)=>{const b=document.createElement('button');b.type='button';b.hidden=i>=6;b.setAttribute('aria-label','Ampliar foto: '+caption);const img=document.createElement('img');img.src='assets/lucas-'+String(i+1).padStart(2,'0')+'.jpg';img.alt=caption;img.loading='lazy';const label=document.createElement('span');label.textContent=caption;b.append(img,label);b.addEventListener('click',()=>{opener=b;current=i;showPhoto();dialog.showModal();});gallery.append(b);});
function showPhoto(){document.getElementById('large-photo').src='assets/lucas-'+String(current+1).padStart(2,'0')+'.jpg';document.getElementById('large-photo').alt=captions[current];document.getElementById('photo-caption').textContent=captions[current];}
document.getElementById('show-more').addEventListener('click',function(){const expanded=this.getAttribute('aria-expanded')==='true';[...gallery.children].forEach((b,i)=>b.hidden=i>=6&&expanded);this.setAttribute('aria-expanded',String(!expanded));this.textContent=expanded?'Ver mais momentos':'Mostrar menos';});
dialog.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>opener?.focus());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
function move(delta){current=(current+delta+captions.length)%captions.length;showPhoto();}document.getElementById('previous').addEventListener('click',()=>move(-1));document.getElementById('next').addEventListener('click',()=>move(1));dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1);});
if(FESTA.horario){document.getElementById('party-time').textContent=FESTA.horario.replace(':','h');document.getElementById('time-note').textContent='Esperamos você!';document.getElementById('count-note').textContent='Contagem para o início da festa.';}
const target=new Date(FESTA.data+'T'+(FESTA.horario||'00:00')+':00-03:00').getTime();function tick(){const diff=target-Date.now();if(diff<=0){document.getElementById('count-grid').hidden=true;document.getElementById('count-grid').style.display='none';document.getElementById('count-note').hidden=true;document.getElementById('count-heading').textContent=Date.now()<new Date(FESTA.data+'T23:59:59-03:00').getTime()?'É hoje! Vamos celebrar!':'Memórias de uma aventura especial.';return;}document.getElementById('days').textContent=Math.floor(diff/86400000);document.getElementById('hours').textContent=Math.floor(diff/3600000)%24;document.getElementById('minutes').textContent=Math.floor(diff/60000)%60;}tick();setInterval(tick,30000);
